program InventarioFisico;

{$R *.dres}

uses
  System.StartUpCopy,
  FMX.Forms,
  Colectora in 'Colectora.pas' {Form4},
  ConfigCliente in 'ConfigCliente.pas' {fConfigCliente},
  Configuracion in 'Configuracion.pas' {fConfiguracion},
  MainActivity in 'MainActivity.pas' {fMainActivity},
  Presentacion in 'Presentacion.pas' {fPresentacion},
  Usuario in 'Usuario.pas' {User},
  Androidapi.JNI.Toasts in 'Librerias_Android\Androidapi.JNI.Toasts.pas',
  AndroidApi.ProgressDialog in 'Librerias_Android\AndroidApi.ProgressDialog.pas',
  FGX.ActionSheet.Android in 'Librerias_Android\FGX.ActionSheet.Android.pas',
  FGX.ActionSheet in 'Librerias_Android\FGX.ActionSheet.pas',
  FGX.ActionSheet.Types in 'Librerias_Android\FGX.ActionSheet.Types.pas',
  FGX.Animations in 'Librerias_Android\FGX.Animations.pas',
  FGX.ApplicationEvents in 'Librerias_Android\FGX.ApplicationEvents.pas',
  FGX.Asserts in 'Librerias_Android\FGX.Asserts.pas',
  FGX.BitBtn in 'Librerias_Android\FGX.BitBtn.pas',
  FGX.Colors.Presets in 'Librerias_Android\FGX.Colors.Presets.pas',
  FGX.ColorsPanel in 'Librerias_Android\FGX.ColorsPanel.pas',
  FGX.Consts in 'Librerias_Android\FGX.Consts.pas',
  FGX.FlipView.Effect in 'Librerias_Android\FGX.FlipView.Effect.pas',
  FGX.FlipView in 'Librerias_Android\FGX.FlipView.pas',
  FGX.FlipView.Presentation in 'Librerias_Android\FGX.FlipView.Presentation.pas',
  FGX.FlipView.Sliding in 'Librerias_Android\FGX.FlipView.Sliding.pas',
  FGX.FlipView.Types in 'Librerias_Android\FGX.FlipView.Types.pas',
  FGX.GradientEdit in 'Librerias_Android\FGX.GradientEdit.pas',
  FGX.Graphics in 'Librerias_Android\FGX.Graphics.pas',
  FGX.Helpers.Android in 'Librerias_Android\FGX.Helpers.Android.pas',
  FGX.Helpers in 'Librerias_Android\FGX.Helpers.pas',
  FGX.Images.Types in 'Librerias_Android\FGX.Images.Types.pas',
  FGX.Items in 'Librerias_Android\FGX.Items.pas',
  FGX.LinkedLabel.Android in 'Librerias_Android\FGX.LinkedLabel.Android.pas',
  FGX.LinkedLabel in 'Librerias_Android\FGX.LinkedLabel.pas',
  FGX.ProgressDialog.Android in 'Librerias_Android\FGX.ProgressDialog.Android.pas',
  FGX.ProgressDialog in 'Librerias_Android\FGX.ProgressDialog.pas',
  FGX.ProgressDialog.Types in 'Librerias_Android\FGX.ProgressDialog.Types.pas',
  FGX.Toasts.Android in 'Librerias_Android\FGX.Toasts.Android.pas',
  FGX.Toasts in 'Librerias_Android\FGX.Toasts.pas',
  FGX.Toolbar in 'Librerias_Android\FGX.Toolbar.pas',
  FGX.Types in 'Librerias_Android\FGX.Types.pas',
  FGX.Types.StateValue in 'Librerias_Android\FGX.Types.StateValue.pas',
  FGX.VirtualKeyboard in 'Librerias_Android\FGX.VirtualKeyboard.pas',
  FGX.VirtualKeyboard.Types in 'Librerias_Android\FGX.VirtualKeyboard.Types.pas',
  ClientClassesUnit1 in 'ClientClassesUnit1.pas',
  ClientModuleUnit1 in 'ClientModuleUnit1.pas' {ClientModule1: TDataModule},
  EditarInventario in 'EditarInventario.pas' {fEditarInventario},
  LecturaCamara in 'LecturaCamara.pas' {MainForm},
  ZXing.OneD.Code39Reader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.Code39Reader.pas',
  ZXing.OneD.Code93Reader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.Code93Reader.pas',
  ZXing.OneD.Code128Reader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.Code128Reader.pas',
  ZXing.OneD.EAN8Reader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.EAN8Reader.pas',
  ZXing.OneD.EAN13Reader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.EAN13Reader.pas',
  ZXing.OneD.EANManufacturerOrgSupport in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.EANManufacturerOrgSupport.pas',
  ZXing.OneD.ITFReader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.ITFReader.pas',
  ZXing.OneD.OneDReader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.OneDReader.pas',
  ZXing.OneD.UPCAReader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.UPCAReader.pas',
  ZXing.OneD.UPCEANExtension2Support in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension2Support.pas',
  ZXing.OneD.UPCEANExtension5Support in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.UPCEANExtension5Support.pas',
  ZXing.OneD.UPCEANExtensionSupport in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.UPCEANExtensionSupport.pas',
  ZXing.OneD.UPCEANReader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.UPCEANReader.pas',
  ZXing.OneD.UPCEReader in 'Librerias_Escaner_Camara\Classes\1D Barcodes\ZXing.OneD.UPCEReader.pas',
  ZXing.Datamatrix.Internal.BitMatrixParser in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  ZXing.Datamatrix.Internal.DataBlock in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DataBlock.pas',
  ZXing.Datamatrix.Internal.DecodedBitStreamParser in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  ZXing.Datamatrix.Internal.Decoder in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Decoder.pas',
  ZXing.Datamatrix.Internal.Version in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.Datamatrix.Internal.Version.pas',
  ZXing.QrCode.Internal.BitMatrixParser in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.BitMatrixParser.pas',
  ZXing.QrCode.Internal.DataBlock in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataBlock.pas',
  ZXing.QrCode.Internal.DataMask in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DataMask.pas',
  ZXing.QrCode.Internal.DecodedBitStreamParser in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  ZXing.QrCode.Internal.Decoder in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Decoder.pas',
  ZXing.QrCode.Internal.ErrorCorrectionLevel in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  ZXing.QrCode.Internal.FormatInformation in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.FormatInformation.pas',
  ZXing.QrCode.Internal.Mode in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Mode.pas',
  ZXing.QrCode.Internal.QRCodeDecoderMetaData in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  ZXing.QrCode.Internal.Version in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Decoder\ZXing.QrCode.Internal.Version.pas',
  ZXing.Datamatrix.Internal.Detector in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.Datamatrix.Internal.Detector.pas',
  ZXing.QrCode.Internal.AlignmentPattern in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPattern.pas',
  ZXing.QrCode.Internal.AlignmentPatternFinder in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  ZXing.QrCode.Internal.AlignmentPatternImplementation in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  ZXing.QrCode.Internal.Detector in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.Detector.pas',
  ZXing.QrCode.Internal.FinderPattern in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPattern.pas',
  ZXing.QrCode.Internal.FinderPatternFinder in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternFinder.pas',
  ZXing.QrCode.Internal.FinderPatternImplementation in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  ZXing.QrCode.Internal.FinderPatternInfo in 'Librerias_Escaner_Camara\Classes\2D Barcodes\Detector\ZXing.QrCode.Internal.FinderPatternInfo.pas',
  ZXing.Datamatrix.DataMatrixReader in 'Librerias_Escaner_Camara\Classes\2D Barcodes\ZXing.Datamatrix.DataMatrixReader.pas',
  ZXing.QrCode.QRCodeReader in 'Librerias_Escaner_Camara\Classes\2D Barcodes\ZXing.QrCode.QRCodeReader.pas',
  ZXing.Common.Detector.MathUtils in 'Librerias_Escaner_Camara\Classes\Common\Detector\ZXing.Common.Detector.MathUtils.pas',
  ZXing.Common.Detector.WhiteRectangleDetector in 'Librerias_Escaner_Camara\Classes\Common\Detector\ZXing.Common.Detector.WhiteRectangleDetector.pas',
  ZXing.Common.ReedSolomon.GenericGF in 'Librerias_Escaner_Camara\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.GenericGF.pas',
  ZXing.Common.ReedSolomon.ReedSolomonDecoder in 'Librerias_Escaner_Camara\Classes\Common\ReedSolomon\ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  ZXing.BarcodeFormat in 'Librerias_Escaner_Camara\Classes\Common\ZXing.BarcodeFormat.pas',
  ZXing.BitSource in 'Librerias_Escaner_Camara\Classes\Common\ZXing.BitSource.pas',
  ZXIng.ByteSegments in 'Librerias_Escaner_Camara\Classes\Common\ZXIng.ByteSegments.pas',
  ZXing.CharacterSetECI in 'Librerias_Escaner_Camara\Classes\Common\ZXing.CharacterSetECI.pas',
  ZXing.Common.BitArray in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Common.BitArray.pas',
  ZXing.Common.BitArrayImplementation in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Common.BitArrayImplementation.pas',
  ZXing.Common.BitMatrix in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Common.BitMatrix.pas',
  ZXing.Common.DetectorResult in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Common.DetectorResult.pas',
  ZXing.Common.GridSampler in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Common.GridSampler.pas',
  ZXing.Common.PerspectiveTransform in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Common.PerspectiveTransform.pas',
  ZXing.DecodeHintType in 'Librerias_Escaner_Camara\Classes\Common\ZXing.DecodeHintType.pas',
  ZXing.DecoderResult in 'Librerias_Escaner_Camara\Classes\Common\ZXing.DecoderResult.pas',
  ZXing.DefaultGridSampler in 'Librerias_Escaner_Camara\Classes\Common\ZXing.DefaultGridSampler.pas',
  ZXing.EncodeHintType in 'Librerias_Escaner_Camara\Classes\Common\ZXing.EncodeHintType.pas',
  ZXing.Helpers in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Helpers.pas',
  ZXing.MultiFormatReader in 'Librerias_Escaner_Camara\Classes\Common\ZXing.MultiFormatReader.pas',
  ZXing.Reader in 'Librerias_Escaner_Camara\Classes\Common\ZXing.Reader.pas',
  ZXing.ReadResult in 'Librerias_Escaner_Camara\Classes\Common\ZXing.ReadResult.pas',
  ZXing.ResultMetadataType in 'Librerias_Escaner_Camara\Classes\Common\ZXing.ResultMetadataType.pas',
  ZXing.ResultPoint in 'Librerias_Escaner_Camara\Classes\Common\ZXing.ResultPoint.pas',
  ZXing.ResultPointImplementation in 'Librerias_Escaner_Camara\Classes\Common\ZXing.ResultPointImplementation.pas',
  ZXing.StringUtils in 'Librerias_Escaner_Camara\Classes\Common\ZXing.StringUtils.pas',
  ZXing.BaseLuminanceSource in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.BaseLuminanceSource.pas',
  ZXing.Binarizer in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.Binarizer.pas',
  ZXing.BinaryBitmap in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.BinaryBitmap.pas',
  ZXing.GlobalHistogramBinarizer in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.GlobalHistogramBinarizer.pas',
  ZXing.HybridBinarizer in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.HybridBinarizer.pas',
  ZXing.InvertedLuminanceSource in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.InvertedLuminanceSource.pas',
  ZXing.LuminanceSource in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.LuminanceSource.pas',
  ZXing.PlanarYUVLuminanceSource in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.PlanarYUVLuminanceSource.pas',
  ZXing.RGBLuminanceSource in 'Librerias_Escaner_Camara\Classes\Filtering\ZXing.RGBLuminanceSource.pas',
  ZXing.ScanManager in 'Librerias_Escaner_Camara\Classes\ZXing.ScanManager.pas',
  KeyboardDemoForm in 'C:\Users\Public\Documents\Embarcadero\Studio\19.0\Samples\Object Pascal\Multi-Device Samples\User Interface\ScrollableForm\KeyboardDemoForm.pas' {FormMain};

{$R *.res}

begin
  Application.Initialize;
  Application.FormFactor.Orientations := [TFormOrientation.Portrait];
  Application.CreateForm(TfMainActivity, fMainActivity);
  Application.CreateForm(TfConfiguracion, fConfiguracion);
  Application.CreateForm(TClientModule1, ClientModule1);
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
